# –°–∫–∞—á–∏–≤–∞–µ–º promtail (–°—Ç–æ–ª–∫–Ω—É–ª—Å—è —Å –ø—Ä–æ–±–ª–µ–º–æ–π –Ω–µ–¥–æ—Å–∫–∞—á–∏–≤–∞–Ω–∏—è ü§∑‚Äç‚ôÄÔ∏è)
# - name: Download promtail binary zip
#   get_url:
#     url: "{{ promtail_download_url }}"
#     dest: "/tmp/promtail-linux-amd64.zip"


- name: Extract an archive
  ansible.builtin.unarchive:
    #src: "/tmp/promtail-linux-amd64.zip"
    src: "/vagrant/ansible/files/promtail-linux-amd64.zip"
    dest: "/usr/local/bin"
    extra_opts: ["-o"]      # Optional: overwrite existing files
    mode: '0555'            # Optional: set mode of extracted files
    remote_src: yes

- name: Copy promtail.service (unit for systemd)
  template:
    src: promtail.service
    dest: /etc/systemd/system
  notify: service promtail restart

- name: Copy promtail configuration
  template:
    src: promtail-config.yml
    dest: /opt/promtail-config.yml
  notify: service promtail restart

# - name: Load promtail unit and start it
#   systemd:
#     name: promtail
#     state: started
#     daemon_reload: true
#     enabled: true 
